Parallelize scripts.

diff --git a/scripts/df-push b/scripts/df-push
--- a/scripts/df-push
+++ b/scripts/df-push
@@ -1,28 +1,40 @@
 #!/bin/sh
 
+# push changes back to repo
+
 basedir="$( cd -P "$( dirname "$0" )" && pwd )"/..
 
 trap "exit 0" SIGINT
 
+# clean up old jobs output
+rm -rf /tmp/df-push-output
+mkdir /tmp/df-push-output
+
+# enable job control
+set -m
+
+push(){
+    if [ -d ".hg" ]; then
+        hg ci -q
+        hg push > /tmp/df-push-output/$1 2>&1 &
+    else
+        git push
+    fi
+}
+
 cd $basedir
-if [ -d ".hg" ]; then
-    hg ci
-    hg push
-else
-    git commit -a
-    git push
-fi
+push dotfiles
 
 for dir in `find . -mindepth 2 -maxdepth 2 \
     -name '.hg' -o \
     -name '.git' | cut -d / -f 2 | sort`; do
 
     cd $basedir/$dir
-    if [ -d ".hg" ]; then
-        hg ci
-        hg push
-    else
-        git commit -a
-        git push
-    fi
+    push $dir
 done
+
+# wait for parallel jobs to finish
+while [ 1 ]; do fg &> /dev/null; [ $? == 1 ] && break; done
+
+# print output
+cat /tmp/df-push-output/*
diff --git a/scripts/df-status b/scripts/df-status
--- a/scripts/df-status
+++ b/scripts/df-status
@@ -6,28 +6,33 @@ basedir="$( cd -P "$( dirname "$0" )" && pwd )"/..
 
 trap "exit 0" SIGINT
 
-cd $basedir
+# clean up old jobs output
+rm -rf /tmp/df-st-output
+mkdir /tmp/df-st-output
 
-if [ -d ".hg" ]; then
-    echo -e "\033[1mdotfiles\033[0m `hg id -n`" | sed 's/\-e //'
-    hg status
-    hg diff --stat
-else
-    echo -e "\033[1mdotfiles\033[0m `git rev-parse --short HEAD`" | sed 's/\-e //'
-    git status
-fi
+# enable job control
+set -m
+
+checkstatus(){
+    if [ -d ".hg" ]; then
+        echo -e "\033[1m$1\033[0m `hg id -n`" | sed 's/\-e //' > /tmp/df-st-output/$1
+        hg diff --stat >> /tmp/df-st-output/$1 2>&1 &
+    else
+        git status
+    fi
+}
+
+cd $basedir
+checkstatus dotfiles
 
 for dir in `find . -mindepth 2 -maxdepth 2 -name '.hg' -o -name '.git' | cut -d / -f 2 | sort`; do
     cd $basedir/$dir
     name="`pwd | rev | cut -d / -f1 | rev`"
-
-    if [ -d ".hg" ]; then
-        echo -e "\033[1m$name\033[0m `hg id -n`" | sed 's/\-e //'
-        hg status
-        hg diff --stat
-    else
-        echo -e "\033[1m$name\033[0m `git rev-parse --short HEAD`" | sed 's/\-e //'
-        git status
-    fi
-
+    checkstatus $dir
 done
+
+# wait for parallel jobs to finish
+while [ 1 ]; do fg &> /dev/null; [ $? == 1 ] && break; done
+
+# print output
+cat /tmp/df-st-output/*
diff --git a/scripts/df-up b/scripts/df-up
--- a/scripts/df-up
+++ b/scripts/df-up
@@ -1,24 +1,37 @@
 #!/bin/sh
 
-basedir="$( cd -P "$( dirname "$0" )" && pwd )"/..
+# updates repos
 
-cd $basedir
+basedir="$( cd -P "$( dirname "$0" )" && pwd )"/..
 
 trap "exit 0" SIGINT
 
-if [ -d ".hg" ]; then
-    hg fetch
-else
-    git pull
-fi
+# clean up old jobs output
+rm -rf /tmp/df-up-output
+mkdir /tmp/df-up-output
 
-for dir in `find . -mindepth 2 -maxdepth 2 -name '.hg' -o -name '.git' | cut -d / -f 2 | sort`; do
-    cd $basedir/$dir
+# enable job control
+set -m
 
+update(){
     if [ -d ".hg" ]; then
-        hg fetch
+        echo -e "\033[1m$1 updated\033[0m" | sed 's/\-e //' > /tmp/df-up-output/$1
+        hg fetch >> /tmp/df-up-output/$1 2>&1 &
     else
         git pull
     fi
+}
 
+cd $basedir
+update dotfiles
+
+for dir in `find . -mindepth 2 -maxdepth 2 -name '.hg' -o -name '.git' | cut -d / -f 2 | sort`; do
+    cd $basedir/$dir
+    update $dir
 done
+
+# wait for parallel jobs to finish
+while [ 1 ]; do fg &> /dev/null; [ $? == 1 ] && break; done
+
+# print output
+cat /tmp/df-up-output/*
